# Generated by Django 4.2.1 on 2023-07-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
